#!/bin/bash
data=( `cat /usr/local/etc/xray/config.json | grep '^###vless' | cut -d ' ' -f 2`);
now=`date +"%Y-%m-%d"`
for user in "${data[@]}"
do
exp=$(grep -w "^###vless $user" "/usr/local/etc/xray/config.json" | cut -d ' ' -f 3)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)
exp2=$(( (d1 - d2) / 86400 ))
#echo "Aktif: $user $exp"
todaystime=`date +%s`
if [ $d1 -ge $todaystime ] ;
then
timeto7days=$(( $todaystime + 604800 ))
if [ $d1 -le $timeto7days ];
then
echo "Aktif: $user $exp"
fi
else
echo "Expired : $user $exp"
sed -i "/###vless $user $exp/d" /usr/local/etc/xray/config.json
sed -i "/vless-$user-$exp/d" /usr/local/etc/xray/config.json
service v2ray restart
service xray restart
fi
done
#echo "belum ada user expired"


