#!/bin/bash
rm -r /var/log/*
mkdir /var/log/apache2
mkdir /var/log/apt
mkdir /var/log/dist-upgrade
mkdir /var/log/install
mkdir /var/log/journal
mkdir /var/log/landscape
mkdir /var/log/letsencrypt
mkdir /var/log/lxd
mkdir /var/log/nginx
mkdir /var/log/openvpn
mkdir /var/log/stunnel4
mkdir /var/log/unattended-upgrades
systemctl restart ws-epro
systemctl restart nginx
systemctl restart trojan
exptrojan
systemctl restart xray
exp-vmess
systemctl restart stunnel4
systemctl restart sshd
rm /root/.bash_history
