#!/bin/bash
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
tendang
sleep 2;
