#!/bin/bash
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
tendang
sleep 1;
